# Generated by Django 6.0 on 2026-01-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_obj', models.ImageField(help_text='The image that was transcribed', null=True, upload_to='')),
                ('text_obj', models.TextField(help_text='The text that was inputted')),
                ('is_question', models.BooleanField(help_text='Whether the text is a question or solution', null=True)),
                ('transcript', models.TextField(help_text='The transcribed text from the image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transcription was created')),
            ],
            options={
                'verbose_name_plural': 'Analysis Transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_obj', models.ImageField(help_text='The image that was transcribed', null=True, upload_to='')),
                ('text_obj', models.TextField(help_text='The text that was inputted')),
                ('transcript', models.TextField(help_text='The transcribed text from the image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transcription was created')),
            ],
            options={
                'verbose_name_plural': 'Analysis Transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(help_text='The problem context')),
                ('attempt', models.TextField(help_text='The attempt context')),
                ('title', models.CharField(blank=True, help_text='The title of the analysis', max_length=250)),
                ('tags', models.JSONField(blank=True, default=list, help_text='The concept tags')),
                ('praise', models.TextField(blank=True, help_text='The part the student got right')),
                ('diagnosis', models.TextField(blank=True, help_text='What the student got wrong')),
                ('explanation', models.TextField(blank=True, help_text='The Feynman explanation generated by the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was created')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_analysi_created_9f353a_idx'), models.Index(fields=['title'], name='api_analysi_title_e4ad53_idx'), models.Index(fields=['title', '-created_at'], name='api_analysi_title_591ef1_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymSesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', help_text='The status of the gym session', max_length=20)),
                ('num_questions', models.IntegerField(default=1, help_text='The number of questions the user solved')),
                ('score', models.IntegerField(blank=True, default=0, help_text='The number of questions answered correctly')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the gym session started')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user started the gym session', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the gym session ended', null=True)),
                ('analysis', models.ForeignKey(help_text='The analysis the gym session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='Gym_analyses', to='api.analysis')),
            ],
            options={
                'verbose_name': 'Gym Sesh',
                'verbose_name_plural': 'Gym Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('evaluating', 'Evaluated'), ('evaluated', 'Evaluated'), ('error', 'Error')], db_index=True, default='pending', help_text='The status of the question', max_length=20)),
                ('question', models.TextField(help_text='The question text')),
                ('question_number', models.IntegerField(help_text='The question number')),
                ('attempt', models.TextField(blank=True, help_text="The user's answer")),
                ('is_correct', models.BooleanField(default=False, help_text="Is the user's answer correct")),
                ('feedback', models.TextField(blank=True, help_text="The models feedback on the user's attempt")),
                ('solution', models.TextField(blank=True, help_text='The models solution to the problem')),
                ('is_answered', models.BooleanField(default=False, help_text='Whether the question has been answered')),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the question was answered', null=True)),
                ('gym_sesh', models.ForeignKey(help_text='The gym session the questions belong to', on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='api.gymsesh')),
            ],
            options={
                'verbose_name': 'Gym Question',
                'verbose_name_plural': 'Gym Questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='gymsesh',
            index=models.Index(fields=['-created_at'], name='api_gymsesh_created_1ba5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='gymsesh',
            index=models.Index(fields=['analysis', '-created_at'], name='api_gymsesh_analysi_3e41b6_idx'),
        ),
        migrations.AddIndex(
            model_name='gymsesh',
            index=models.Index(fields=['analysis', 'status'], name='api_gymsesh_analysi_ff3ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='gymquestions',
            index=models.Index(fields=['is_correct'], name='api_gymques_is_corr_65fb41_idx'),
        ),
        migrations.AddIndex(
            model_name='gymquestions',
            index=models.Index(fields=['gym_sesh', 'is_correct'], name='api_gymques_gym_ses_12746b_idx'),
        ),
        migrations.AddIndex(
            model_name='gymquestions',
            index=models.Index(fields=['status', 'gym_sesh'], name='api_gymques_status_bad94c_idx'),
        ),
    ]
