from typing import Any
from django.db import models

class AnalysisTranscript(models.Model):
    """Store the transcribed images from the analysis"""
    image_obj = models.ImageField(null=True, help_text="The image that was transcribed")
    text_obj = models.TextField(help_text="The text that was inputted")
    is_question = models.BooleanField(null=True, help_text="Whether the text is a question or solution")
    transcript = models.TextField(help_text="The transcribed text from the image")
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the transcription was created")

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = "Analysis Transcripts"

    def __str__(self) -> str:
        return f"Transcript {self.id} - Question: {self.is_question}"
    
class GymTranscript(models.Model):
    """Stores the transcribed images from the gym analysis"""
    image_obj = models.ImageField(null=True, help_text="The image that was transcribed")
    text_obj = models.TextField(help_text="The text that was inputted")
    transcript = models.TextField(help_text="The transcribed text from the image")
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the transcription was created")

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = "Analysis Transcripts"

    def __str__(self) -> str:
        return f"Transcript {self.id} - created at {self.created_at.strftime('%Y-%m-%d %H:%M')}"
    
class Analysis(models.Model):
    """Stores the analysis result and parameters"""
    problem = models.TextField(help_text="The problem context")
    attempt = models.TextField(help_text="The attempt context")
    title = models.CharField(max_length=200, blank=True, help_text="The title of the analysis")
    tags = models.JSONField(default=list, blank=True, help_text="The concept tags")
    praise = models.TextField(blank=True, help_text="The part the student got right")
    diagnosis = models.TextField(blank=True, help_text="What the student got wrong")
    explanation = models.TextField(blank=True, help_text="The Feynman explanation generated by the AI")
    practice_problem = models.TextField(blank=True, help_text="The practice problem to test the user's knowledge")
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the analysis was created")

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Analysis'
        verbose_name_plural = 'Analyses'
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['title']),
            models.Index(fields=['title, -created_at'])
        ]

    def __str__(self)-> str:
        return f"Analysis {self.title or 'Untitled'} - created at {self.created_at.strftime('%Y-%m-%d %H:$M')}"
    
    @property
    def to_dict(self):
        """Converts the analysis to dictionary format"""
        return {
            'id': self.id,
            'problem': self.problem,
            'attempt': self.attempt,
            'title': self.title,
            'tags': self.tags,
            'praise': self.praise,
            'diagnosis': self.diagnosis,
            'explanation': self.explanation,
            'practice_problem': self.practice_problem,
            'created_at': self.created_at.isoformat()
        }